-- CreateTable
CREATE TABLE "pokemons" (
    "id" BIGSERIAL NOT NULL,
    "pokedex_number" BIGINT,
    "name" TEXT,
    "german_name" TEXT,
    "japanese_name" TEXT,
    "generation" BIGINT,
    "status" TEXT,
    "species" TEXT,
    "type_number" BIGINT,
    "type_1" TEXT,
    "type_2" TEXT,
    "height_m" DOUBLE PRECISION,
    "weight_kg" TEXT,
    "abilities_number" BIGINT,
    "ability_1" TEXT,
    "ability_2" TEXT,
    "ability_hidden" TEXT,
    "total_points" BIGINT,
    "hp" BIGINT,
    "attack" BIGINT,
    "defense" BIGINT,
    "sp_attack" BIGINT,
    "sp_defense" BIGINT,
    "speed" BIGINT,
    "catch_rate" TEXT,
    "base_friendship" TEXT,
    "base_experience" TEXT,
    "growth_rate" TEXT,
    "egg_type_number" BIGINT,
    "egg_type_1" TEXT,
    "egg_type_2" TEXT,
    "percentage_male" TEXT,
    "egg_cycles" TEXT,
    "against_normal" DOUBLE PRECISION,
    "against_fire" DOUBLE PRECISION,
    "against_water" DOUBLE PRECISION,
    "against_electric" DOUBLE PRECISION,
    "against_grass" DOUBLE PRECISION,
    "against_ice" DOUBLE PRECISION,
    "against_fight" DOUBLE PRECISION,
    "against_poison" DOUBLE PRECISION,
    "against_ground" DOUBLE PRECISION,
    "against_flying" DOUBLE PRECISION,
    "against_psychic" DOUBLE PRECISION,
    "against_bug" DOUBLE PRECISION,
    "against_rock" DOUBLE PRECISION,
    "against_ghost" DOUBLE PRECISION,
    "against_dragon" DOUBLE PRECISION,
    "against_dark" DOUBLE PRECISION,
    "against_steel" DOUBLE PRECISION,
    "against_fairy" DOUBLE PRECISION,

    CONSTRAINT "pokemons_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "pokemons_id_key" ON "pokemons"("id");
